import { describe, expect, it } from "vitest";

import { generateSemanticTokens } from "@/helpers/generateSemanticTokens";

describe("generateSemanticTokens", () => {
  it("generates correct semantic token structure if useDarkMode & useP3 is true", () => {
    const semanticTokens = generateSemanticTokens(true, true, ["gray"]);
    expect(semanticTokens).toEqual({
      "gray":{
        "1":{ "value":{ "base":"{colors.gray.light.1}","_dark":"{colors.gray.dark.1}" } },
        "2":{ "value":{ "base":"{colors.gray.light.2}","_dark":"{colors.gray.dark.2}" } },
        "3":{ "value":{ "base":"{colors.gray.light.3}","_dark":"{colors.gray.dark.3}" } },
        "4":{ "value":{ "base":"{colors.gray.light.4}","_dark":"{colors.gray.dark.4}" } },
        "5":{ "value":{ "base":"{colors.gray.light.5}","_dark":"{colors.gray.dark.5}" } },
        "6":{ "value":{ "base":"{colors.gray.light.6}","_dark":"{colors.gray.dark.6}" } },
        "7":{ "value":{ "base":"{colors.gray.light.7}","_dark":"{colors.gray.dark.7}" } },
        "8":{ "value":{ "base":"{colors.gray.light.8}","_dark":"{colors.gray.dark.8}" } },
        "9":{ "value":{ "base":"{colors.gray.light.9}","_dark":"{colors.gray.dark.9}" } },
        "10":{ "value":{ "base":"{colors.gray.light.10}","_dark":"{colors.gray.dark.10}" } },
        "11":{ "value":{ "base":"{colors.gray.light.11}","_dark":"{colors.gray.dark.11}" } },
        "12":{ "value":{ "base":"{colors.gray.light.12}","_dark":"{colors.gray.dark.12}" } },
        "light":{
          "1":{ "value":{ "base":"#fcfcfc","_p3":"{colors.gray.light.p3.1}" } },
          "2":{ "value":{ "base":"#f9f9f9","_p3":"{colors.gray.light.p3.2}" } },
          "3":{ "value":{ "base":"#f0f0f0","_p3":"{colors.gray.light.p3.3}" } },
          "4":{ "value":{ "base":"#e8e8e8","_p3":"{colors.gray.light.p3.4}" } },
          "5":{ "value":{ "base":"#e0e0e0","_p3":"{colors.gray.light.p3.5}" } },
          "6":{ "value":{ "base":"#d9d9d9","_p3":"{colors.gray.light.p3.6}" } },
          "7":{ "value":{ "base":"#cecece","_p3":"{colors.gray.light.p3.7}" } },
          "8":{ "value":{ "base":"#bbbbbb","_p3":"{colors.gray.light.p3.8}" } },
          "9":{ "value":{ "base":"#8d8d8d","_p3":"{colors.gray.light.p3.9}" } },
          "10":{ "value":{ "base":"#838383","_p3":"{colors.gray.light.p3.10}" } },
          "11":{ "value":{ "base":"#646464","_p3":"{colors.gray.light.p3.11}" } },
          "12":{ "value":{ "base":"#202020","_p3":"{colors.gray.light.p3.12}" } },
          "a":{
            "1":{ "value":{ "base":"#00000003","_p3":"{colors.gray.light.p3.a.1}" } },
            "2":{ "value":{ "base":"#00000006","_p3":"{colors.gray.light.p3.a.2}" } },
            "3":{ "value":{ "base":"#0000000f","_p3":"{colors.gray.light.p3.a.3}" } },
            "4":{ "value":{ "base":"#00000017","_p3":"{colors.gray.light.p3.a.4}" } },
            "5":{ "value":{ "base":"#0000001f","_p3":"{colors.gray.light.p3.a.5}" } },
            "6":{ "value":{ "base":"#00000026","_p3":"{colors.gray.light.p3.a.6}" } },
            "7":{ "value":{ "base":"#00000031","_p3":"{colors.gray.light.p3.a.7}" } },
            "8":{ "value":{ "base":"#00000044","_p3":"{colors.gray.light.p3.a.8}" } },
            "9":{ "value":{ "base":"#00000072","_p3":"{colors.gray.light.p3.a.9}" } },
            "10":{ "value":{ "base":"#0000007c","_p3":"{colors.gray.light.p3.a.10}" } },
            "11":{ "value":{ "base":"#0000009b","_p3":"{colors.gray.light.p3.a.11}" } },
            "12":{ "value":{ "base":"#000000df","_p3":"{colors.gray.light.p3.a.12}" } },
          },
          "p3":{
            "1":{ "value":"color(display-p3 0.988 0.988 0.988)" },
            "2":{ "value":"color(display-p3 0.975 0.975 0.975)" },
            "3":{ "value":"color(display-p3 0.939 0.939 0.939)" },
            "4":{ "value":"color(display-p3 0.908 0.908 0.908)" },
            "5":{ "value":"color(display-p3 0.88 0.88 0.88)" },
            "6":{ "value":"color(display-p3 0.849 0.849 0.849)" },
            "7":{ "value":"color(display-p3 0.807 0.807 0.807)" },
            "8":{ "value":"color(display-p3 0.732 0.732 0.732)" },
            "9":{ "value":"color(display-p3 0.553 0.553 0.553)" },
            "10":{ "value":"color(display-p3 0.512 0.512 0.512)" },
            "11":{ "value":"color(display-p3 0.392 0.392 0.392)" },
            "12":{ "value":"color(display-p3 0.125 0.125 0.125)" },
            "a":{
              "1":{ "value":"color(display-p3 0 0 0 / 0.012)" },
              "2":{ "value":"color(display-p3 0 0 0 / 0.024)" },
              "3":{ "value":"color(display-p3 0 0 0 / 0.063)" },
              "4":{ "value":"color(display-p3 0 0 0 / 0.09)" },
              "5":{ "value":"color(display-p3 0 0 0 / 0.122)" },
              "6":{ "value":"color(display-p3 0 0 0 / 0.153)" },
              "7":{ "value":"color(display-p3 0 0 0 / 0.192)" },
              "8":{ "value":"color(display-p3 0 0 0 / 0.267)" },
              "9":{ "value":"color(display-p3 0 0 0 / 0.447)" },
              "10":{ "value":"color(display-p3 0 0 0 / 0.486)" },
              "11":{ "value":"color(display-p3 0 0 0 / 0.608)" },
              "12":{ "value":"color(display-p3 0 0 0 / 0.875)" },
            },
          },
        },
        "dark":{
          "1":{ "value":{ "base":"#111111","_p3":"{colors.gray.dark.p3.1}" } },
          "2":{ "value":{ "base":"#191919","_p3":"{colors.gray.dark.p3.2}" } },
          "3":{ "value":{ "base":"#222222","_p3":"{colors.gray.dark.p3.3}" } },
          "4":{ "value":{ "base":"#2a2a2a","_p3":"{colors.gray.dark.p3.4}" } },
          "5":{ "value":{ "base":"#313131","_p3":"{colors.gray.dark.p3.5}" } },
          "6":{ "value":{ "base":"#3a3a3a","_p3":"{colors.gray.dark.p3.6}" } },
          "7":{ "value":{ "base":"#484848","_p3":"{colors.gray.dark.p3.7}" } },
          "8":{ "value":{ "base":"#606060","_p3":"{colors.gray.dark.p3.8}" } },
          "9":{ "value":{ "base":"#6e6e6e","_p3":"{colors.gray.dark.p3.9}" } },
          "10":{ "value":{ "base":"#7b7b7b","_p3":"{colors.gray.dark.p3.10}" } },
          "11":{ "value":{ "base":"#b4b4b4","_p3":"{colors.gray.dark.p3.11}" } },
          "12":{ "value":{ "base":"#eeeeee","_p3":"{colors.gray.dark.p3.12}" } },
          "a":{
            "1":{ "value":{ "base":"#00000000","_p3":"{colors.gray.dark.p3.a.1}" } },
            "2":{ "value":{ "base":"#ffffff09","_p3":"{colors.gray.dark.p3.a.2}" } },
            "3":{ "value":{ "base":"#ffffff12","_p3":"{colors.gray.dark.p3.a.3}" } },
            "4":{ "value":{ "base":"#ffffff1b","_p3":"{colors.gray.dark.p3.a.4}" } },
            "5":{ "value":{ "base":"#ffffff22","_p3":"{colors.gray.dark.p3.a.5}" } },
            "6":{ "value":{ "base":"#ffffff2c","_p3":"{colors.gray.dark.p3.a.6}" } },
            "7":{ "value":{ "base":"#ffffff3b","_p3":"{colors.gray.dark.p3.a.7}" } },
            "8":{ "value":{ "base":"#ffffff55","_p3":"{colors.gray.dark.p3.a.8}" } },
            "9":{ "value":{ "base":"#ffffff64","_p3":"{colors.gray.dark.p3.a.9}" } },
            "10":{ "value":{ "base":"#ffffff72","_p3":"{colors.gray.dark.p3.a.10}" } },
            "11":{ "value":{ "base":"#ffffffaf","_p3":"{colors.gray.dark.p3.a.11}" } },
            "12":{ "value":{ "base":"#ffffffed","_p3":"{colors.gray.dark.p3.a.12}" } },
          },
          "p3":{
            "1":{ "value":"color(display-p3 0.067 0.067 0.067)" },
            "2":{ "value":"color(display-p3 0.098 0.098 0.098)" },
            "3":{ "value":"color(display-p3 0.135 0.135 0.135)" },
            "4":{ "value":"color(display-p3 0.163 0.163 0.163)" },
            "5":{ "value":"color(display-p3 0.192 0.192 0.192)" },
            "6":{ "value":"color(display-p3 0.228 0.228 0.228)" },
            "7":{ "value":"color(display-p3 0.283 0.283 0.283)" },
            "8":{ "value":"color(display-p3 0.375 0.375 0.375)" },
            "9":{ "value":"color(display-p3 0.431 0.431 0.431)" },
            "10":{ "value":"color(display-p3 0.484 0.484 0.484)" },
            "11":{ "value":"color(display-p3 0.706 0.706 0.706)" },
            "12":{ "value":"color(display-p3 0.933 0.933 0.933)" },
            "a":{
              "1":{ "value":"color(display-p3 0 0 0 / 0)" },
              "2":{ "value":"color(display-p3 1 1 1 / 0.034)" },
              "3":{ "value":"color(display-p3 1 1 1 / 0.071)" },
              "4":{ "value":"color(display-p3 1 1 1 / 0.105)" },
              "5":{ "value":"color(display-p3 1 1 1 / 0.134)" },
              "6":{ "value":"color(display-p3 1 1 1 / 0.172)" },
              "7":{ "value":"color(display-p3 1 1 1 / 0.231)" },
              "8":{ "value":"color(display-p3 1 1 1 / 0.332)" },
              "9":{ "value":"color(display-p3 1 1 1 / 0.391)" },
              "10":{ "value":"color(display-p3 1 1 1 / 0.445)" },
              "11":{ "value":"color(display-p3 1 1 1 / 0.685)" },
              "12":{ "value":"color(display-p3 1 1 1 / 0.929)" },
            },
          },
        },
        "a":{
          "1":{ "value":{ "base":"{colors.gray.light.a.1}","_dark":"{colors.gray.dark.a.1}" } },
          "2":{ "value":{ "base":"{colors.gray.light.a.2}","_dark":"{colors.gray.dark.a.2}" } },
          "3":{ "value":{ "base":"{colors.gray.light.a.3}","_dark":"{colors.gray.dark.a.3}" } },
          "4":{ "value":{ "base":"{colors.gray.light.a.4}","_dark":"{colors.gray.dark.a.4}" } },
          "5":{ "value":{ "base":"{colors.gray.light.a.5}","_dark":"{colors.gray.dark.a.5}" } },
          "6":{ "value":{ "base":"{colors.gray.light.a.6}","_dark":"{colors.gray.dark.a.6}" } },
          "7":{ "value":{ "base":"{colors.gray.light.a.7}","_dark":"{colors.gray.dark.a.7}" } },
          "8":{ "value":{ "base":"{colors.gray.light.a.8}","_dark":"{colors.gray.dark.a.8}" } },
          "9":{ "value":{ "base":"{colors.gray.light.a.9}","_dark":"{colors.gray.dark.a.9}" } },
          "10":{ "value":{ "base":"{colors.gray.light.a.10}","_dark":"{colors.gray.dark.a.10}" } },
          "11":{ "value":{ "base":"{colors.gray.light.a.11}","_dark":"{colors.gray.dark.a.11}" } },
          "12":{ "value":{ "base":"{colors.gray.light.a.12}","_dark":"{colors.gray.dark.a.12}" } },
        },
        "p3":{
          "1":{ "value":{ "base":"{colors.gray.light.p3.1}","_dark":"{colors.gray.dark.p3.1}" } },
          "2":{ "value":{ "base":"{colors.gray.light.p3.2}","_dark":"{colors.gray.dark.p3.2}" } },
          "3":{ "value":{ "base":"{colors.gray.light.p3.3}","_dark":"{colors.gray.dark.p3.3}" } },
          "4":{ "value":{ "base":"{colors.gray.light.p3.4}","_dark":"{colors.gray.dark.p3.4}" } },
          "5":{ "value":{ "base":"{colors.gray.light.p3.5}","_dark":"{colors.gray.dark.p3.5}" } },
          "6":{ "value":{ "base":"{colors.gray.light.p3.6}","_dark":"{colors.gray.dark.p3.6}" } },
          "7":{ "value":{ "base":"{colors.gray.light.p3.7}","_dark":"{colors.gray.dark.p3.7}" } },
          "8":{ "value":{ "base":"{colors.gray.light.p3.8}","_dark":"{colors.gray.dark.p3.8}" } },
          "9":{ "value":{ "base":"{colors.gray.light.p3.9}","_dark":"{colors.gray.dark.p3.9}" } },
          "10":{ "value":{ "base":"{colors.gray.light.p3.10}","_dark":"{colors.gray.dark.p3.10}" } },
          "11":{ "value":{ "base":"{colors.gray.light.p3.11}","_dark":"{colors.gray.dark.p3.11}" } },
          "12":{ "value":{ "base":"{colors.gray.light.p3.12}","_dark":"{colors.gray.dark.p3.12}" } },
          "a":{
            "1":{ "value":{ "base":"{colors.gray.light.p3.a.1}","_dark":"{colors.gray.dark.p3.a.1}" } },
            "2":{ "value":{ "base":"{colors.gray.light.p3.a.2}","_dark":"{colors.gray.dark.p3.a.2}" } },
            "3":{ "value":{ "base":"{colors.gray.light.p3.a.3}","_dark":"{colors.gray.dark.p3.a.3}" } },
            "4":{ "value":{ "base":"{colors.gray.light.p3.a.4}","_dark":"{colors.gray.dark.p3.a.4}" } },
            "5":{ "value":{ "base":"{colors.gray.light.p3.a.5}","_dark":"{colors.gray.dark.p3.a.5}" } },
            "6":{ "value":{ "base":"{colors.gray.light.p3.a.6}","_dark":"{colors.gray.dark.p3.a.6}" } },
            "7":{ "value":{ "base":"{colors.gray.light.p3.a.7}","_dark":"{colors.gray.dark.p3.a.7}" } },
            "8":{ "value":{ "base":"{colors.gray.light.p3.a.8}","_dark":"{colors.gray.dark.p3.a.8}" } },
            "9":{ "value":{ "base":"{colors.gray.light.p3.a.9}","_dark":"{colors.gray.dark.p3.a.9}" } },
            "10":{ "value":{ "base":"{colors.gray.light.p3.a.10}","_dark":"{colors.gray.dark.p3.a.10}" } },
            "11":{ "value":{ "base":"{colors.gray.light.p3.a.11}","_dark":"{colors.gray.dark.p3.a.11}" } },
            "12":{ "value":{ "base":"{colors.gray.light.p3.a.12}","_dark":"{colors.gray.dark.p3.a.12}" } },
          },
        },
      },
    });
  });

  it("generates correct semantic token structure if useDarkMode is true and useP3 is false", () => {
    const semanticTokens = generateSemanticTokens(true, false, ["gray"]);
    expect(semanticTokens).toEqual({
      "gray":{
        "1":{ "value":{ "base":"{colors.gray.light.1}","_dark":"{colors.gray.dark.1}" } },
        "2":{ "value":{ "base":"{colors.gray.light.2}","_dark":"{colors.gray.dark.2}" } },
        "3":{ "value":{ "base":"{colors.gray.light.3}","_dark":"{colors.gray.dark.3}" } },
        "4":{ "value":{ "base":"{colors.gray.light.4}","_dark":"{colors.gray.dark.4}" } },
        "5":{ "value":{ "base":"{colors.gray.light.5}","_dark":"{colors.gray.dark.5}" } },
        "6":{ "value":{ "base":"{colors.gray.light.6}","_dark":"{colors.gray.dark.6}" } },
        "7":{ "value":{ "base":"{colors.gray.light.7}","_dark":"{colors.gray.dark.7}" } },
        "8":{ "value":{ "base":"{colors.gray.light.8}","_dark":"{colors.gray.dark.8}" } },
        "9":{ "value":{ "base":"{colors.gray.light.9}","_dark":"{colors.gray.dark.9}" } },
        "10":{ "value":{ "base":"{colors.gray.light.10}","_dark":"{colors.gray.dark.10}" } },
        "11":{ "value":{ "base":"{colors.gray.light.11}","_dark":"{colors.gray.dark.11}" } },
        "12":{ "value":{ "base":"{colors.gray.light.12}","_dark":"{colors.gray.dark.12}" } },
        "light":{
          "1":{ "value":{ "base":"#fcfcfc" } },
          "2":{ "value":{ "base":"#f9f9f9" } },
          "3":{ "value":{ "base":"#f0f0f0" } },
          "4":{ "value":{ "base":"#e8e8e8" } },
          "5":{ "value":{ "base":"#e0e0e0" } },
          "6":{ "value":{ "base":"#d9d9d9" } },
          "7":{ "value":{ "base":"#cecece" } },
          "8":{ "value":{ "base":"#bbbbbb" } },
          "9":{ "value":{ "base":"#8d8d8d" } },
          "10":{ "value":{ "base":"#838383" } },
          "11":{ "value":{ "base":"#646464" } },
          "12":{ "value":{ "base":"#202020" } },
          "a":{
            "1":{ "value":{ "base":"#00000003" } },
            "2":{ "value":{ "base":"#00000006" } },
            "3":{ "value":{ "base":"#0000000f" } },
            "4":{ "value":{ "base":"#00000017" } },
            "5":{ "value":{ "base":"#0000001f" } },
            "6":{ "value":{ "base":"#00000026" } },
            "7":{ "value":{ "base":"#00000031" } },
            "8":{ "value":{ "base":"#00000044" } },
            "9":{ "value":{ "base":"#00000072" } },
            "10":{ "value":{ "base":"#0000007c" } },
            "11":{ "value":{ "base":"#0000009b" } },
            "12":{ "value":{ "base":"#000000df" } },
          },
        },
        "dark":{
          "1":{ "value":{ "base":"#111111" } },
          "2":{ "value":{ "base":"#191919" } },
          "3":{ "value":{ "base":"#222222" } },
          "4":{ "value":{ "base":"#2a2a2a" } },
          "5":{ "value":{ "base":"#313131" } },
          "6":{ "value":{ "base":"#3a3a3a" } },
          "7":{ "value":{ "base":"#484848" } },
          "8":{ "value":{ "base":"#606060" } },
          "9":{ "value":{ "base":"#6e6e6e" } },
          "10":{ "value":{ "base":"#7b7b7b" } },
          "11":{ "value":{ "base":"#b4b4b4" } },
          "12":{ "value":{ "base":"#eeeeee" } },
          "a":{
            "1":{ "value":{ "base":"#00000000" } },
            "2":{ "value":{ "base":"#ffffff09" } },
            "3":{ "value":{ "base":"#ffffff12" } },
            "4":{ "value":{ "base":"#ffffff1b" } },
            "5":{ "value":{ "base":"#ffffff22" } },
            "6":{ "value":{ "base":"#ffffff2c" } },
            "7":{ "value":{ "base":"#ffffff3b" } },
            "8":{ "value":{ "base":"#ffffff55" } },
            "9":{ "value":{ "base":"#ffffff64" } },
            "10":{ "value":{ "base":"#ffffff72" } },
            "11":{ "value":{ "base":"#ffffffaf" } },
            "12":{ "value":{ "base":"#ffffffed" } },
          },
        },
        "a":{
          "1":{ "value":{ "base":"{colors.gray.light.a.1}","_dark":"{colors.gray.dark.a.1}" } },
          "2":{ "value":{ "base":"{colors.gray.light.a.2}","_dark":"{colors.gray.dark.a.2}" } },
          "3":{ "value":{ "base":"{colors.gray.light.a.3}","_dark":"{colors.gray.dark.a.3}" } },
          "4":{ "value":{ "base":"{colors.gray.light.a.4}","_dark":"{colors.gray.dark.a.4}" } },
          "5":{ "value":{ "base":"{colors.gray.light.a.5}","_dark":"{colors.gray.dark.a.5}" } },
          "6":{ "value":{ "base":"{colors.gray.light.a.6}","_dark":"{colors.gray.dark.a.6}" } },
          "7":{ "value":{ "base":"{colors.gray.light.a.7}","_dark":"{colors.gray.dark.a.7}" } },
          "8":{ "value":{ "base":"{colors.gray.light.a.8}","_dark":"{colors.gray.dark.a.8}" } },
          "9":{ "value":{ "base":"{colors.gray.light.a.9}","_dark":"{colors.gray.dark.a.9}" } },
          "10":{ "value":{ "base":"{colors.gray.light.a.10}","_dark":"{colors.gray.dark.a.10}" } },
          "11":{ "value":{ "base":"{colors.gray.light.a.11}","_dark":"{colors.gray.dark.a.11}" } },
          "12":{ "value":{ "base":"{colors.gray.light.a.12}","_dark":"{colors.gray.dark.a.12}" } },
        },
      },
    });
  });

  it("generates correct semantic token structure if useDarkMode & useP3 is false", () => {
    const semanticTokens = generateSemanticTokens(false, false, ["gray"]);
    expect(semanticTokens).toEqual({
      "gray":{
        "1":{ "value":{ "base":"{colors.gray.light.1}" } },
        "2":{ "value":{ "base":"{colors.gray.light.2}" } },
        "3":{ "value":{ "base":"{colors.gray.light.3}" } },
        "4":{ "value":{ "base":"{colors.gray.light.4}" } },
        "5":{ "value":{ "base":"{colors.gray.light.5}" } },
        "6":{ "value":{ "base":"{colors.gray.light.6}" } },
        "7":{ "value":{ "base":"{colors.gray.light.7}" } },
        "8":{ "value":{ "base":"{colors.gray.light.8}" } },
        "9":{ "value":{ "base":"{colors.gray.light.9}" } },
        "10":{ "value":{ "base":"{colors.gray.light.10}" } },
        "11":{ "value":{ "base":"{colors.gray.light.11}" } },
        "12":{ "value":{ "base":"{colors.gray.light.12}" } },
        "light":{
          "1":{ "value":{ "base":"#fcfcfc" } },
          "2":{ "value":{ "base":"#f9f9f9" } },
          "3":{ "value":{ "base":"#f0f0f0" } },
          "4":{ "value":{ "base":"#e8e8e8" } },
          "5":{ "value":{ "base":"#e0e0e0" } },
          "6":{ "value":{ "base":"#d9d9d9" } },
          "7":{ "value":{ "base":"#cecece" } },
          "8":{ "value":{ "base":"#bbbbbb" } },
          "9":{ "value":{ "base":"#8d8d8d" } },
          "10":{ "value":{ "base":"#838383" } },
          "11":{ "value":{ "base":"#646464" } },
          "12":{ "value":{ "base":"#202020" } },
          "a":{
            "1":{ "value":{ "base":"#00000003" } },
            "2":{ "value":{ "base":"#00000006" } },
            "3":{ "value":{ "base":"#0000000f" } },
            "4":{ "value":{ "base":"#00000017" } },
            "5":{ "value":{ "base":"#0000001f" } },
            "6":{ "value":{ "base":"#00000026" } },
            "7":{ "value":{ "base":"#00000031" } },
            "8":{ "value":{ "base":"#00000044" } },
            "9":{ "value":{ "base":"#00000072" } },
            "10":{ "value":{ "base":"#0000007c" } },
            "11":{ "value":{ "base":"#0000009b" } },
            "12":{ "value":{ "base":"#000000df" } },
          },
        },
        "a":{
          "1":{ "value":{ "base":"{colors.gray.light.a.1}" } },
          "2":{ "value":{ "base":"{colors.gray.light.a.2}" } },
          "3":{ "value":{ "base":"{colors.gray.light.a.3}" } },
          "4":{ "value":{ "base":"{colors.gray.light.a.4}" } },
          "5":{ "value":{ "base":"{colors.gray.light.a.5}" } },
          "6":{ "value":{ "base":"{colors.gray.light.a.6}" } },
          "7":{ "value":{ "base":"{colors.gray.light.a.7}" } },
          "8":{ "value":{ "base":"{colors.gray.light.a.8}" } },
          "9":{ "value":{ "base":"{colors.gray.light.a.9}" } },
          "10":{ "value":{ "base":"{colors.gray.light.a.10}" } },
          "11":{ "value":{ "base":"{colors.gray.light.a.11}" } },
          "12":{ "value":{ "base":"{colors.gray.light.a.12}" } },
        },
      },
    });
  });

  it("generates correct semantic token structure if multiple colors are in selectedColors", () => {
    const semanticTokens = generateSemanticTokens(false, false, ["gray", "ruby"]);

    expect(semanticTokens).toEqual({
      "gray":{
        "1":{ "value":{ "base":"{colors.gray.light.1}" } },
        "2":{ "value":{ "base":"{colors.gray.light.2}" } },
        "3":{ "value":{ "base":"{colors.gray.light.3}" } },
        "4":{ "value":{ "base":"{colors.gray.light.4}" } },
        "5":{ "value":{ "base":"{colors.gray.light.5}" } },
        "6":{ "value":{ "base":"{colors.gray.light.6}" } },
        "7":{ "value":{ "base":"{colors.gray.light.7}" } },
        "8":{ "value":{ "base":"{colors.gray.light.8}" } },
        "9":{ "value":{ "base":"{colors.gray.light.9}" } },
        "10":{ "value":{ "base":"{colors.gray.light.10}" } },
        "11":{ "value":{ "base":"{colors.gray.light.11}" } },
        "12":{ "value":{ "base":"{colors.gray.light.12}" } },
        "light":{
          "1":{ "value":{ "base":"#fcfcfc" } },
          "2":{ "value":{ "base":"#f9f9f9" } },
          "3":{ "value":{ "base":"#f0f0f0" } },
          "4":{ "value":{ "base":"#e8e8e8" } },
          "5":{ "value":{ "base":"#e0e0e0" } },
          "6":{ "value":{ "base":"#d9d9d9" } },
          "7":{ "value":{ "base":"#cecece" } },
          "8":{ "value":{ "base":"#bbbbbb" } },
          "9":{ "value":{ "base":"#8d8d8d" } },
          "10":{ "value":{ "base":"#838383" } },
          "11":{ "value":{ "base":"#646464" } },
          "12":{ "value":{ "base":"#202020" } },
          "a":{
            "1":{ "value":{ "base":"#00000003" } },
            "2":{ "value":{ "base":"#00000006" } },
            "3":{ "value":{ "base":"#0000000f" } },
            "4":{ "value":{ "base":"#00000017" } },
            "5":{ "value":{ "base":"#0000001f" } },
            "6":{ "value":{ "base":"#00000026" } },
            "7":{ "value":{ "base":"#00000031" } },
            "8":{ "value":{ "base":"#00000044" } },
            "9":{ "value":{ "base":"#00000072" } },
            "10":{ "value":{ "base":"#0000007c" } },
            "11":{ "value":{ "base":"#0000009b" } },
            "12":{ "value":{ "base":"#000000df" } },
          },
        },
        "a":{
          "1":{ "value":{ "base":"{colors.gray.light.a.1}" } },
          "2":{ "value":{ "base":"{colors.gray.light.a.2}" } },
          "3":{ "value":{ "base":"{colors.gray.light.a.3}" } },
          "4":{ "value":{ "base":"{colors.gray.light.a.4}" } },
          "5":{ "value":{ "base":"{colors.gray.light.a.5}" } },
          "6":{ "value":{ "base":"{colors.gray.light.a.6}" } },
          "7":{ "value":{ "base":"{colors.gray.light.a.7}" } },
          "8":{ "value":{ "base":"{colors.gray.light.a.8}" } },
          "9":{ "value":{ "base":"{colors.gray.light.a.9}" } },
          "10":{ "value":{ "base":"{colors.gray.light.a.10}" } },
          "11":{ "value":{ "base":"{colors.gray.light.a.11}" } },
          "12":{ "value":{ "base":"{colors.gray.light.a.12}" } },
        },
      },
      "ruby":{
        "1":{ "value":{ "base":"{colors.ruby.light.1}" } },
        "2":{ "value":{ "base":"{colors.ruby.light.2}" } },
        "3":{ "value":{ "base":"{colors.ruby.light.3}" } },
        "4":{ "value":{ "base":"{colors.ruby.light.4}" } },
        "5":{ "value":{ "base":"{colors.ruby.light.5}" } },
        "6":{ "value":{ "base":"{colors.ruby.light.6}" } },
        "7":{ "value":{ "base":"{colors.ruby.light.7}" } },
        "8":{ "value":{ "base":"{colors.ruby.light.8}" } },
        "9":{ "value":{ "base":"{colors.ruby.light.9}" } },
        "10":{ "value":{ "base":"{colors.ruby.light.10}" } },
        "11":{ "value":{ "base":"{colors.ruby.light.11}" } },
        "12":{ "value":{ "base":"{colors.ruby.light.12}" } },
        "light":{
          "1":{ "value":{ "base":"#fffcfd" } },
          "2":{ "value":{ "base":"#fff7f8" } },
          "3":{ "value":{ "base":"#feeaed" } },
          "4":{ "value":{ "base":"#ffdce1" } },
          "5":{ "value":{ "base":"#ffced6" } },
          "6":{ "value":{ "base":"#f8bfc8" } },
          "7":{ "value":{ "base":"#efacb8" } },
          "8":{ "value":{ "base":"#e592a3" } },
          "9":{ "value":{ "base":"#e54666" } },
          "10":{ "value":{ "base":"#dc3b5d" } },
          "11":{ "value":{ "base":"#ca244d" } },
          "12":{ "value":{ "base":"#64172b" } },
          "a":{
            "1": { "value": { "base": "#ff005503" } },
            "2": { "value": { "base": "#ff002008" } },
            "3": { "value": { "base": "#f3002515" } },
            "4": { "value": { "base": "#ff002523" } },
            "5": { "value": { "base": "#ff002a31" } },
            "6": { "value": { "base": "#e4002440" } },
            "7": { "value": { "base": "#ce002553" } },
            "8": { "value": { "base": "#c300286d" } },
            "9": { "value": { "base": "#db002cb9" } },
            "10": { "value": { "base": "#d2002cc4" } },
            "11": { "value": { "base": "#c10030db" } },
            "12": { "value": { "base": "#550016e8" } },
          },
        },
        "a":{
          "1":{ "value":{ "base":"{colors.ruby.light.a.1}" } },
          "2":{ "value":{ "base":"{colors.ruby.light.a.2}" } },
          "3":{ "value":{ "base":"{colors.ruby.light.a.3}" } },
          "4":{ "value":{ "base":"{colors.ruby.light.a.4}" } },
          "5":{ "value":{ "base":"{colors.ruby.light.a.5}" } },
          "6":{ "value":{ "base":"{colors.ruby.light.a.6}" } },
          "7":{ "value":{ "base":"{colors.ruby.light.a.7}" } },
          "8":{ "value":{ "base":"{colors.ruby.light.a.8}" } },
          "9":{ "value":{ "base":"{colors.ruby.light.a.9}" } },
          "10":{ "value":{ "base":"{colors.ruby.light.a.10}" } },
          "11":{ "value":{ "base":"{colors.ruby.light.a.11}" } },
          "12":{ "value":{ "base":"{colors.ruby.light.a.12}" } },
        },
      },
    });
  });

  it("generates different semantic token structure for blackA & whiteA colors", () => {
    const semanticTokens = generateSemanticTokens(true, true, ["blackA", "whiteA"]);

    expect(semanticTokens).toEqual({
      "black":{
        "a":{
          "1":{ "value":{ "base":"rgba(0, 0, 0, 0.05)","_p3":"{colors.black.p3.a.1}" } },
          "2":{ "value":{ "base":"rgba(0, 0, 0, 0.1)","_p3":"{colors.black.p3.a.2}" } },
          "3":{ "value":{ "base":"rgba(0, 0, 0, 0.15)","_p3":"{colors.black.p3.a.3}" } },
          "4":{ "value":{ "base":"rgba(0, 0, 0, 0.2)","_p3":"{colors.black.p3.a.4}" } },
          "5":{ "value":{ "base":"rgba(0, 0, 0, 0.3)","_p3":"{colors.black.p3.a.5}" } },
          "6":{ "value":{ "base":"rgba(0, 0, 0, 0.4)","_p3":"{colors.black.p3.a.6}" } },
          "7":{ "value":{ "base":"rgba(0, 0, 0, 0.5)","_p3":"{colors.black.p3.a.7}" } },
          "8":{ "value":{ "base":"rgba(0, 0, 0, 0.6)","_p3":"{colors.black.p3.a.8}" } },
          "9":{ "value":{ "base":"rgba(0, 0, 0, 0.7)","_p3":"{colors.black.p3.a.9}" } },
          "10":{ "value":{ "base":"rgba(0, 0, 0, 0.8)","_p3":"{colors.black.p3.a.10}" } },
          "11":{ "value":{ "base":"rgba(0, 0, 0, 0.9)","_p3":"{colors.black.p3.a.11}" } },
          "12":{ "value":{ "base":"rgba(0, 0, 0, 0.95)","_p3":"{colors.black.p3.a.12}" } },
        },
        "p3":{
          "a":{
            "1":{ "value":"color(display-p3 0 0 0 / 0.05)" },
            "2":{ "value":"color(display-p3 0 0 0 / 0.1)" },
            "3":{ "value":"color(display-p3 0 0 0 / 0.15)" },
            "4":{ "value":"color(display-p3 0 0 0 / 0.2)" },
            "5":{ "value":"color(display-p3 0 0 0 / 0.3)" },
            "6":{ "value":"color(display-p3 0 0 0 / 0.4)" },
            "7":{ "value":"color(display-p3 0 0 0 / 0.5)" },
            "8":{ "value":"color(display-p3 0 0 0 / 0.6)" },
            "9":{ "value":"color(display-p3 0 0 0 / 0.7)" },
            "10":{ "value":"color(display-p3 0 0 0 / 0.8)" },
            "11":{ "value":"color(display-p3 0 0 0 / 0.9)" },
            "12":{ "value":"color(display-p3 0 0 0 / 0.95)" },
          },
        },
      },
      "white":{
        "a":{
          "1":{ "value":{ "base":"rgba(255, 255, 255, 0.05)","_p3":"{colors.white.p3.a.1}" } },
          "2":{ "value":{ "base":"rgba(255, 255, 255, 0.1)","_p3":"{colors.white.p3.a.2}" } },
          "3":{ "value":{ "base":"rgba(255, 255, 255, 0.15)","_p3":"{colors.white.p3.a.3}" } },
          "4":{ "value":{ "base":"rgba(255, 255, 255, 0.2)","_p3":"{colors.white.p3.a.4}" } },
          "5":{ "value":{ "base":"rgba(255, 255, 255, 0.3)","_p3":"{colors.white.p3.a.5}" } },
          "6":{ "value":{ "base":"rgba(255, 255, 255, 0.4)","_p3":"{colors.white.p3.a.6}" } },
          "7":{ "value":{ "base":"rgba(255, 255, 255, 0.5)","_p3":"{colors.white.p3.a.7}" } },
          "8":{ "value":{ "base":"rgba(255, 255, 255, 0.6)","_p3":"{colors.white.p3.a.8}" } },
          "9":{ "value":{ "base":"rgba(255, 255, 255, 0.7)","_p3":"{colors.white.p3.a.9}" } },
          "10":{ "value":{ "base":"rgba(255, 255, 255, 0.8)","_p3":"{colors.white.p3.a.10}" } },
          "11":{ "value":{ "base":"rgba(255, 255, 255, 0.9)","_p3":"{colors.white.p3.a.11}" } },
          "12":{ "value":{ "base":"rgba(255, 255, 255, 0.95)","_p3":"{colors.white.p3.a.12}" } },
        },
        "p3":{
          "a":{
            "1":{ "value":"color(display-p3 1 1 1 / 0.05)" },
            "2":{ "value":"color(display-p3 1 1 1 / 0.1)" },
            "3":{ "value":"color(display-p3 1 1 1 / 0.15)" },
            "4":{ "value":"color(display-p3 1 1 1 / 0.2)" },
            "5":{ "value":"color(display-p3 1 1 1 / 0.3)" },
            "6":{ "value":"color(display-p3 1 1 1 / 0.4)" },
            "7":{ "value":"color(display-p3 1 1 1 / 0.5)" },
            "8":{ "value":"color(display-p3 1 1 1 / 0.6)" },
            "9":{ "value":"color(display-p3 1 1 1 / 0.7)" },
            "10":{ "value":"color(display-p3 1 1 1 / 0.8)" },
            "11":{ "value":"color(display-p3 1 1 1 / 0.9)" },
            "12":{ "value":"color(display-p3 1 1 1 / 0.95)" },
          },
        },
      },
    });
  });

  it("generates correct semantic token structure for blackA & whiteA colors if useDarkMode and useP3 is false", () => {
    const semanticTokens = generateSemanticTokens(false, false, ["blackA", "whiteA"]);

    expect(semanticTokens).toEqual({
      "black":{
        "a":{
          "1":{ "value":{ "base":"rgba(0, 0, 0, 0.05)" } },
          "2":{ "value":{ "base":"rgba(0, 0, 0, 0.1)" } },
          "3":{ "value":{ "base":"rgba(0, 0, 0, 0.15)" } },
          "4":{ "value":{ "base":"rgba(0, 0, 0, 0.2)" } },
          "5":{ "value":{ "base":"rgba(0, 0, 0, 0.3)" } },
          "6":{ "value":{ "base":"rgba(0, 0, 0, 0.4)" } },
          "7":{ "value":{ "base":"rgba(0, 0, 0, 0.5)" } },
          "8":{ "value":{ "base":"rgba(0, 0, 0, 0.6)" } },
          "9":{ "value":{ "base":"rgba(0, 0, 0, 0.7)" } },
          "10":{ "value":{ "base":"rgba(0, 0, 0, 0.8)" } },
          "11":{ "value":{ "base":"rgba(0, 0, 0, 0.9)" } },
          "12":{ "value":{ "base":"rgba(0, 0, 0, 0.95)" } },
        },
      },
      "white":{
        "a":{
          "1":{ "value":{ "base":"rgba(255, 255, 255, 0.05)" } },
          "2":{ "value":{ "base":"rgba(255, 255, 255, 0.1)" } },
          "3":{ "value":{ "base":"rgba(255, 255, 255, 0.15)" } },
          "4":{ "value":{ "base":"rgba(255, 255, 255, 0.2)" } },
          "5":{ "value":{ "base":"rgba(255, 255, 255, 0.3)" } },
          "6":{ "value":{ "base":"rgba(255, 255, 255, 0.4)" } },
          "7":{ "value":{ "base":"rgba(255, 255, 255, 0.5)" } },
          "8":{ "value":{ "base":"rgba(255, 255, 255, 0.6)" } },
          "9":{ "value":{ "base":"rgba(255, 255, 255, 0.7)" } },
          "10":{ "value":{ "base":"rgba(255, 255, 255, 0.8)" } },
          "11":{ "value":{ "base":"rgba(255, 255, 255, 0.9)" } },
          "12":{ "value":{ "base":"rgba(255, 255, 255, 0.95)" } },
        },
      },
    });
  });
});
